spring.application.name: config
server.port: 8888
spring.cloud.config.server.git:
  uri: https://github.com/piotrek722/Microservices
  searchPaths: application-config
  cloneOnStart: true

eureka.client.region : default
eureka.client.registryFetchIntervalSeconds : 5
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/